### ISSUE TITLE
No e-mails recieved

### ISSUE THREAD

**Issue by Thasmeer** [cusatxpress/qaforums#2]
After CusatXpress forum got an update, for the question asked when replied no more e-mail notification is sent to the users.

**Comment by cusatxpress** [comment]
Hello @Thasmeer, we have made cleared the issue for the e-mail. are you still experiencing it ?

**Comment by cusatxpress** [comment]
Hello @Thasmeer,
**Thank you for opening this issue to us.** We resolved the issue and the Emails started working now. 

please see the attached Screenshot, Devil sent us after checking on the issue.

![11122](https://cloud.githubusercontent.com/assets/2988898/16757670/1851b972-482b-11e6-8b8e-be0c38faaafc.PNG)

Thanking you again,
**CusatXpress** Support
